sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  npm i -g npm@^5.3.0
script: npm test
branches:
  only:
    - master